//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCTimer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCTimer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause_16x {
            get {
                object obj = ResourceManager.GetObject("Pause_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartWithoutDebug_16x {
            get {
                object obj = ResourceManager.GetObject("StartWithoutDebug_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t start FTP
        ///{0}.
        /// </summary>
        internal static string TimerForm_CheckBoxFtpChanged_Couldn_t_start_FTP__0_ {
            get {
                return ResourceManager.GetString("TimerForm_CheckBoxFtpChanged_Couldn_t_start_FTP__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select rounds.
        /// </summary>
        internal static string TimerForm_selectRoundsButton_Click_Select_rounds {
            get {
                return ResourceManager.GetString("TimerForm_selectRoundsButton_Click_Select_rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select rounds in which results should be shown.
        /// </summary>
        internal static string TimerForm_selectRoundsButton_Click_Select_rounds_in_which_results_should_be_shown {
            get {
                return ResourceManager.GetString("TimerForm_selectRoundsButton_Click_Select_rounds_in_which_results_should_be_shown" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string TimerForm_TimerForm_FormClosing_Are_you_sure_ {
            get {
                return ResourceManager.GetString("TimerForm_TimerForm_FormClosing_Are_you_sure_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this window?.
        /// </summary>
        internal static string TimerForm_TimerForm_FormClosing_Are_you_sure_you_want_to_close_this_window_ {
            get {
                return ResourceManager.GetString("TimerForm_TimerForm_FormClosing_Are_you_sure_you_want_to_close_this_window_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None selected.
        /// </summary>
        internal static string TimerForm_TimerForm_None_selected {
            get {
                return ResourceManager.GetString("TimerForm_TimerForm_None_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds: .
        /// </summary>
        internal static string TimerForm_UpdateSelectedRoundsLabel_Rounds__ {
            get {
                return ResourceManager.GetString("TimerForm_UpdateSelectedRoundsLabel_Rounds__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round {0}.
        /// </summary>
        internal static string TimerForm_UpdateTime_Round__0_ {
            get {
                return ResourceManager.GetString("TimerForm_UpdateTime_Round__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t update timer file
        ///{0}.
        /// </summary>
        internal static string TimerForm_WriteTournamentTimer_ {
            get {
                return ResourceManager.GetString("TimerForm_WriteTournamentTimer_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t send timer to ftp
        ///{0}.
        /// </summary>
        internal static string TimerForm_WriteTournamentTimer_couldn_t_send_timer_to_ftp_ {
            get {
                return ResourceManager.GetString("TimerForm_WriteTournamentTimer_couldn_t_send_timer_to_ftp_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string TimerForm_WriteTournamentTimer_Something_went_wrong {
            get {
                return ResourceManager.GetString("TimerForm_WriteTournamentTimer_Something_went_wrong", resourceCulture);
            }
        }
    }
}
